const express = require("express");

const router = express.Router();

/**
 * POST /api/export
 *
 * Accepts the full analysis result in the request body and returns
 * a Markdown document summarising the repository analysis.
 */
router.post("/", (req, res) => {
  const data = req.body;

  if (!data || !data.languages) {
    return res.status(400).json({ error: "Analysis data is required in the request body.", code: "MISSING_DATA" });
  }

  try {
    const md = generateMarkdown(data);
    const filename = (data.repoId || "codeatlas-export") + ".md";

    res.setHeader("Content-Type", "text/markdown; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.send(md);
  } catch (err) {
    res.status(500).json({ error: "Export failed", details: err.message });
  }
});

// ---------------------------------------------------------------------------
// Markdown Generator
// ---------------------------------------------------------------------------

function generateMarkdown(data) {
  const lines = [];

  // Title
  const repoName = data.repoId || "Repository";
  lines.push(`# CodeAtlas Report -- ${repoName}`);
  lines.push("");
  lines.push(`> Generated by [CodeAtlas](https://github.com/7sg56/CodeAtlas) on ${new Date().toISOString().split("T")[0]}`);
  lines.push("");

  // ---- Project Overview ----
  lines.push("## Project Overview");
  lines.push("");

  const frameworks = data.frameworks || [];
  if (frameworks.length > 0) {
    lines.push(`**Frameworks:** ${frameworks.join(", ")}`);
  }

  if (data.stats) {
    lines.push(`**Files:** ${data.stats.files}  |  **Folders:** ${data.stats.folders}`);
  }

  if (data.analysis) {
    lines.push(`**AST-Parsed Files:** ${data.analysis.filesAnalyzed}`);
    if (data.analysis.summary) {
      const s = data.analysis.summary;
      lines.push(`**Functions:** ${s.totalFunctions}  |  **Classes:** ${s.totalClasses}  |  **Exports:** ${s.totalExports}  |  **Avg Complexity:** ${s.avgComplexity}`);
    }
  }
  lines.push("");

  // ---- Languages ----
  if (data.languages && data.languages.length > 0) {
    lines.push("## Languages");
    lines.push("");
    lines.push("| Language | Percentage |");
    lines.push("|----------|-----------|");
    for (const lang of data.languages) {
      lines.push(`| ${lang.language} | ${lang.percentage}% |`);
    }
    lines.push("");
  }

  // ---- Entrypoints ----
  if (data.entrypoints && data.entrypoints.length > 0) {
    lines.push("## Entrypoints");
    lines.push("");
    lines.push("| Type | File | Line |");
    lines.push("|------|------|------|");
    for (const ep of data.entrypoints) {
      lines.push(`| ${ep.type.replace(/_/g, " ")} | \`${ep.file}\` | ${ep.line} |`);
    }
    lines.push("");
  }

  // ---- API Routes ----
  if (data.routes && data.routes.length > 0) {
    lines.push("## API Routes");
    lines.push("");
    lines.push("| Method | Path | File | Line | Framework |");
    lines.push("|--------|------|------|------|-----------|");
    for (const r of data.routes) {
      lines.push(`| \`${r.method}\` | \`${r.path}\` | \`${r.file}\` | ${r.line} | ${r.framework} |`);
    }
    lines.push("");
  }

  // ---- Import / Dependency Map ----
  if (data.dependencies && data.dependencies.length > 0) {
    lines.push("## Import / Dependency Map");
    lines.push("");

    // Group dependencies by source file
    const byFrom = {};
    for (const dep of data.dependencies) {
      if (!byFrom[dep.from]) byFrom[dep.from] = [];
      byFrom[dep.from].push(dep.to);
    }

    for (const [file, imports] of Object.entries(byFrom)) {
      lines.push(`### \`${file}\``);
      lines.push("");
      for (const imp of imports) {
        lines.push(`- \`${imp}\``);
      }
      lines.push("");
    }
  }

  // ---- Symbols Summary ----
  if (data.symbols && data.symbols.length > 0) {
    lines.push("## Symbols Summary");
    lines.push("");
    lines.push("| File | Functions | Classes | Exports |");
    lines.push("|------|-----------|---------|---------|");
    for (const s of data.symbols) {
      lines.push(`| \`${s.file}\` | ${s.functions.length} | ${s.classes.length} | ${s.exports.length} |`);
    }
    lines.push("");
  }

  // ---- Complexity Hotspots ----
  if (data.complexity && data.complexity.length > 0) {
    // Collect all functions with complexity >= 5
    const hotspots = [];
    for (const c of data.complexity) {
      for (const f of c.functions) {
        if (f.complexity >= 5) {
          hotspots.push({ file: c.file, ...f });
        }
      }
    }
    if (hotspots.length > 0) {
      hotspots.sort((a, b) => b.complexity - a.complexity);
      lines.push("## Complexity Hotspots");
      lines.push("");
      lines.push("Functions with cyclomatic complexity >= 5:");
      lines.push("");
      lines.push("| File | Function | Complexity | Max Depth |");
      lines.push("|------|----------|-----------|-----------|");
      for (const h of hotspots.slice(0, 30)) {
        lines.push(`| \`${h.file}\` | \`${h.name}\` | ${h.complexity} | ${h.maxDepth} |`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by CodeAtlas*");
  lines.push("");

  return lines.join("\n");
}

module.exports = router;
